# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Excel-Writer-XLSX
version:      0.38
version_from: lib/Excel/Writer/XLSX.pm
installdirs:  site
requires:
    Archive::Zip:                  1.3
    IO::File:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
