--- #YAML:1.0
name:               Excel-Writer-XLSX
version:            0.46
abstract:           Create a new file in the Excel 2007+ XLSX format.
author:
    - John McNamara (jmcnamara@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Zip:  1.3
    File::Temp:    0.19
    IO::File:      1.14
resources:
    homepage:     http://jmcnamara.github.com/excel-writer-xlsx/
    MailingList:  http://groups.google.com/group/spreadsheet-writeexcel
    repository:   http://github.com/jmcnamara/excel-writer-xlsx
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
