---
abstract: 'Create a new file in the Excel 2007+ XLSX format.'
author:
  - 'John McNamara (jmcnamara@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Excel-Writer-XLSX
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Zip: '1.3'
  File::Temp: '0.19'
  IO::File: '1.14'
resources:
  MailingList: http://groups.google.com/group/spreadsheet-writeexcel
  bugtracker: http://github.com/jmcnamara/excel-writer-xlsx/issues
  homepage: http://jmcnamara.github.com/excel-writer-xlsx/
  repository: http://github.com/jmcnamara/excel-writer-xlsx
version: '0.81'
